### ISSUE TITLE
iOS13.3.1 内容编辑键盘收起后，无法再次弹出键盘。

### ISSUE THREAD

**Issue by JamhonyZ** [study123456/WGEditor-mobile#32]
部分系统出现首次进入页面 点击空白处可以弹出键盘，点击收起之后，就无法再唤起内容键盘。（点击标题 再 切换内容，是可以看到内容编辑的键盘，但想通过正文唤起键盘 就是不行）。
iOS系统13.3.1，机型iPhoneX 和 XR。
 13.4没有这个bug。

**Comment by JamhonyZ** [comment]
找到解决方案了，遇到问题的朋友们看这里。
在webView代理decidePolicyForNavigationAction里 写现场睡眠0.05秒。
if ([[[UIDevice currentDevice] systemVersion] containsString:@"13.3"]) {
      [NSThread sleepForTimeInterval:0.05];
    }
    [self.webView updatePlaceHolderStatu];
    [self fontBarUpdateWithString:urlString];
    [self handleEvent:urlString];
    [self handleWithString:urlString];

**Comment by bugaio** [comment]
对我而言,   加上这   ios13  新的 方法就可以了...
```
- (void)webView:(WKWebView *)webView decidePolicyForNavigationAction:(WKNavigationAction *)navigationAction preferences:(WKWebpagePreferences *)preferences decisionHandler:(void (^)(WKNavigationActionPolicy, WKWebpagePreferences * _Nonnull))decisionHandler  API_AVAILABLE(ios(13.0)){
    
    decisionHandler(WKNavigationActionPolicyAllow,preferences); // 必须实现 加载
}
```

**Comment by tph-ux** [comment]
What the fuck are you giving me?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"骑猪o0o找牛"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月20日(星期三) 下午3:17
收件人:&nbsp;"study123456/WGEditor-mobile"<WGEditor-mobile@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [study123456/WGEditor-mobile] iOS13.3.1 内容编辑键盘收起后，无法再次弹出键盘。 (#32)





 
对我而言,   加上这   ios13  新的 方法就可以了...
 - (void)webView:(WKWebView *)webView decidePolicyForNavigationAction:(WKNavigationAction *)navigationAction preferences:(WKWebpagePreferences *)preferences decisionHandler:(void (^)(WKNavigationActionPolicy, WKWebpagePreferences * _Nonnull))decisionHandler  API_AVAILABLE(ios(13.0)){          decisionHandler(WKNavigationActionPolicyAllow,preferences); // 必须实现 加载 }

**Comment by JamhonyZ** [comment]
> What the fuck are you giving me?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"骑猪o0o找牛"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月20日(星期三) 下午3:17 收件人:&nbsp;"study123456/WGEditor-mobile"<WGEditor-mobile@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [study123456/WGEditor-mobile] iOS13.3.1 内容编辑键盘收起后，无法再次弹出键盘。 (#32) 对我而言, 加上这 ios13 新的 方法就可以了... - (void)webView:(WKWebView *)webView decidePolicyForNavigationAction:(WKNavigationAction *)navigationAction preferences:(WKWebpagePreferences *)preferences decisionHandler:(void (^)(WKNavigationActionPolicy, WKWebpagePreferences * _Nonnull))decisionHandler API_AVAILABLE(ios(13.0)){ decisionHandler(WKNavigationActionPolicyAllow,preferences); // 必须实现 加载 } — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

are you hanpi
